deep_cfr_tf1:
  game: kuhn_poker
  num_players: 2
  policy_network_layers: !!python/tuple [16, 8]
  advantage_network_layers: !!python/tuple [8, 4]
  num_iterations: 100
  num_traversals: 20
  learning_rate: 0.001
  num_steps: 5
  checkpoint_dir: /tmp/deep_cfr_tf1
  save_every: 1
  eval_every: 1

deep_cfr_tf2:
  game: kuhn_poker
  num_players: 2
  policy_network_layers: !!python/tuple [256, 256]
  advantage_network_layers: !!python/tuple [128, 128]
  num_iterations: 2
  num_traversals: 2
  batch_size_advantage: 8
  batch_size_strategy: 8
  learning_rate: 0.0001
  num_steps: 100
  policy_network_train_steps: 5000
  advantage_network_train_steps: 750
  checkpoint_dir: /tmp/deep_cfr_tf2
  save_every: 1
  eval_every: 1

tabular_cfr:
  game: kuhn_poker
  num_players: 2
  

dqn:
  game: kuhn_poker
  num_players: 2
  hidden_layers_sizes: [8]
  replay_buffer_capacity: 100
  batch_size: 128
  num_steps: 100
  learning_rate: 0.01
  epsilon_start: 0.02
  epsilon_end: 0.01
  checkpoint_dir: /tmp/dqn
  save_every: 1
  eval_every: 1

  

  